/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProtectU;

import java.awt.Color;
import java.util.Scanner;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author shaun
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public SignUp() {
        //errorText.setBackground(Color.white);
        initComponents();
        
    }
    
    public boolean passwordsMatch = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        pnumber = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        ecnumber = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        age = new javax.swing.JSpinner();
        confirmLabel = new javax.swing.JLabel();
        p2 = new javax.swing.JPasswordField();
        p1 = new javax.swing.JPasswordField();
        signUp = new javax.swing.JButton();
        baack1 = new javax.swing.JButton();
        ageLabel = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        errorText = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        emergencyNumberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(430, 640, 640, 640));
        setMaximumSize(new java.awt.Dimension(430, 640));
        setMinimumSize(new java.awt.Dimension(430, 640));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        passwordLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordLabel.setText("PASSWORD");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(80, 500, 90, 17);

        nameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel.setText("FIRST NAME");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(60, 200, 86, 17);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProtectU/PU_LogoSmall.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(140, 0, 150, 140);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Noto Sans Oriya", 3, 24)); // NOI18N
        jLabel1.setText("Welcome to the ProtectU Family");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 80, 430, 100);

        lastNameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastNameLabel.setText("LAST NAME");
        jPanel1.add(lastNameLabel);
        lastNameLabel.setBounds(60, 240, 90, 17);

        phoneNumberLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phoneNumberLabel.setText("PHONE NUMBER");
        jPanel1.add(phoneNumberLabel);
        phoneNumberLabel.setBounds(30, 280, 120, 17);

        emailLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel.setText("EMAIL");
        jPanel1.add(emailLabel);
        emailLabel.setBounds(50, 360, 60, 17);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname);
        fname.setBounds(160, 190, 220, 30);

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel1.add(lname);
        lname.setBounds(160, 230, 220, 30);

        pnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnumberActionPerformed(evt);
            }
        });
        jPanel1.add(pnumber);
        pnumber.setBounds(160, 270, 220, 30);

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        jPanel1.add(city);
        city.setBounds(110, 440, 270, 30);

        genderLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        genderLabel.setText("GENDER");
        jPanel1.add(genderLabel);
        genderLabel.setBounds(190, 400, 70, 30);

        ecnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecnumberActionPerformed(evt);
            }
        });
        jPanel1.add(ecnumber);
        ecnumber.setBounds(200, 310, 180, 30);

        cityLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cityLabel.setText("TOWN");
        jPanel1.add(cityLabel);
        cityLabel.setBounds(50, 450, 50, 17);
        jPanel1.add(age);
        age.setBounds(80, 400, 80, 30);

        confirmLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmLabel.setText("CONFIRM PASSWORD");
        jPanel1.add(confirmLabel);
        confirmLabel.setBounds(10, 540, 160, 17);

        p2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                p2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p2KeyTyped(evt);
            }
        });
        jPanel1.add(p2);
        p2.setBounds(180, 530, 200, 30);
        jPanel1.add(p1);
        p1.setBounds(180, 490, 200, 30);

        signUp.setFont(new java.awt.Font("Noto Sans Oriya", 1, 20)); // NOI18N
        signUp.setForeground(new java.awt.Color(0, 153, 255));
        signUp.setText("SIGN UP");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        jPanel1.add(signUp);
        signUp.setBounds(290, 600, 130, 30);

        baack1.setFont(new java.awt.Font("Noto Sans Oriya", 1, 20)); // NOI18N
        baack1.setText("BACK");
        baack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baack1ActionPerformed(evt);
            }
        });
        jPanel1.add(baack1);
        baack1.setBounds(10, 600, 100, 30);

        ageLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ageLabel.setText("AGE");
        jPanel1.add(ageLabel);
        ageLabel.setBounds(40, 400, 30, 30);

        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender);
        gender.setBounds(260, 400, 120, 30);

        errorText.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        errorText.setForeground(new java.awt.Color(102, 204, 255));
        errorText.setText("PLEASE VALIDATE PASSWORD");
        jPanel1.add(errorText);
        errorText.setBounds(120, 570, 190, 14);
        jPanel1.add(email);
        email.setBounds(110, 353, 270, 30);

        emergencyNumberLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emergencyNumberLabel.setText("EMERGENCY CONTACT");
        jPanel1.add(emergencyNumberLabel);
        emergencyNumberLabel.setBounds(30, 320, 170, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void pnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnumberActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void ecnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecnumberActionPerformed

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        // TODO add your handling code here:
        /*
        JOptionPane.showMessageDialog(null,"THANKS FOR JOINING....");
        
        */
        nameLabel.setForeground(Color.black);
        lastNameLabel.setForeground(Color.black);
        phoneNumberLabel.setForeground(Color.black);
        emailLabel.setForeground(Color.black);
        cityLabel.setForeground(Color.black);
        age.setForeground(Color.black);
        genderLabel.setForeground(Color.black);
        p1.setForeground(Color.black);
        p2.setForeground(Color.black);
        
        UserClass uc = new UserClass();
        GPSClass gps = new GPSClass();
        int areaCode = gps.areaCodeFinder(city.getText());
        
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+"[a-zA-Z0-9_+&*-]+)*@" + "(?:[a-zA-Z0-9-]+\\.)+[a-z" + "A-Z]{2,7}$";
        Pattern pat = Pattern.compile(emailRegex);
        
        if(fname.getText().length() < 2){
            nameLabel.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "MISSING FIELDS","TRY AGAIN", JOptionPane.PLAIN_MESSAGE);
        }
        else if(lname.getText().length() < 2){
            lastNameLabel.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "MISSING FIELDS","TRY AGAIN", JOptionPane.PLAIN_MESSAGE);
        }
        else if(pnumber.getText().length() < 9){
            phoneNumberLabel.setForeground(Color.red);
            Scanner sc = new Scanner(pnumber.getText());
            if(!sc.hasNextInt()){
                phoneNumberLabel.setForeground(Color.red);
            }
            phoneNumberLabel.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "MISSING/INVALID NUMBER","TRY AGAIN", JOptionPane.PLAIN_MESSAGE);
        }
        else if(ecnumber.getText().length() < 9){
            Scanner sc = new Scanner(ecnumber.getText());
            if(!sc.hasNextInt()){
                emergencyNumberLabel.setForeground(Color.red);
            }
            emergencyNumberLabel.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "MISSING/INVALID NUMBER","TRY AGAIN", JOptionPane.PLAIN_MESSAGE);
        }
        else if(pat.matcher(email.getText()).matches() == false){
            emailLabel.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, email.getText() + " IS NOT A VALID EMAIL","TRY AGAIN", JOptionPane.PLAIN_MESSAGE);
        }
        else if(age.getValue().toString().equals(0)){
            JOptionPane.showMessageDialog(null, "PLEASE SELECT VALID AGE","TRY AGAIN", JOptionPane.PLAIN_MESSAGE);
            age.setForeground(Color.red);
        }
        else if(gender.getText().length() < 3){
            JOptionPane.showMessageDialog(null, "PLEASE ENTER GENDER'","TRY AGAIN", JOptionPane.PLAIN_MESSAGE);
            genderLabel.setForeground(Color.red);
        }
        else if(areaCode == 0){
            cityLabel.setForeground(Color.red);
        }
        else if(p1.getText().length() < 3 && p2.getText().length() < 3){
            passwordLabel.setForeground(Color.red);
            confirmLabel.setForeground(Color.red);
        }
        else if(passwordsMatch == false){
            JOptionPane.showMessageDialog(null, "PASSWORDS DO NOT MATCH PLEASE TRY AGAIN","TRY AGAIN", JOptionPane.PLAIN_MESSAGE);
        }
        else{
            
            uc.newUser(fname.getText(),lname.getText(), pnumber.getText(),email.getText(),areaCode , ecnumber.getText(),Integer.parseInt(age.getValue().toString()), gender.getText(), p2.getText());
            Login lg = new Login();
            lg.setVisible(true);
            dispose();
        }
        
        //uc.newUser(fname.getText(), lname.getText(), pnumber.getText(), p2.getText(),1, address.getText(), ecnumber.getText() , Integer.parseInt(age.getValue().toString()), gender.getText());
    }//GEN-LAST:event_signUpActionPerformed

    private void baack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baack1ActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_baack1ActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void p2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p2KeyTyped

    }//GEN-LAST:event_p2KeyTyped

    private void p2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p2KeyReleased
        if(p2.getText().equals(p1.getText()) == false){
            errorText.setForeground(Color.red);
            errorText.setText("PASSWORDS DO NOT MATCH");
        }
        else if(p2.getText().equals(p1.getText()) == true){
            errorText.setForeground(Color.GREEN);
            errorText.setText("PASSWORDS MACTH");
            passwordsMatch = true;
        }
    }//GEN-LAST:event_p2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner age;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton baack1;
    private javax.swing.JTextField city;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JTextField ecnumber;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emergencyNumberLabel;
    private static javax.swing.JLabel errorText;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField pnumber;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables
}
